### ISSUE TITLE
Adding ConSo_onto.csv

### ISSUE THREAD

**Issue by akalino** [PhungLai728/OnML#1]
From the README:

Run python3 onto.py to get information from ontology. Note that ConSo_onto.csv was generated directly from an ontology in Protégé (Protégé 5.5.0-beta-9 was used in this project) and an add-on Export to CSV

Could you please add to either the repo or the google drive? Thanks!

We will discuss at next meeting the steps used to generate the ontology outputs from Protege (such as which entities are exported, etc.).

**Comment by PhungLai728** [comment]
I have just added the ConSo_onto.csv to data folder. Thanks!

**Comment by PhungLai728** [comment]
Please follow this link to add the Excel plugin to Protege. Thanks
https://github.com/protegeproject/csv-export-plugin

**Comment by akalino** [comment]
Thanks!
