### ISSUE TITLE
Still missing vectorizer

### ISSUE THREAD

**Issue by akalino** [PhungLai728/OnML#2]
https://github.com/PhungLai728/OnML/blob/c8cd3a6ce0a4dfd7ab6223fa068ea6b970a31bd6/reproduce/Prediction_model/lstm_cc.py#L74

@PhungLai728 I am still missing the code to generate the vectorizer. This is later loaded with the model to create the sk-learn pipeline.

**Comment by PhungLai728** [comment]
Hi, in the updated version of main_cc.py, we do not need to use vectorizer.p. That's why I did not upload that file. Is there any place that you still need to have the vectorizer, please let me know! Thanks

**Comment by akalino** [comment]
I see the change now, thanks for clarifying. I will close both issues as resolved.

**Comment by akalino** [comment]
@PhungLai728 I think there is one final missing piece in main_cc called sorted_cc.npz. Could you let me know how that is generated? Thanks

**Comment by PhungLai728** [comment]
hi actually, the `sorted_cc.npz` contains a sorted list of complaint orders. It is based on the number of ontology-based tuples found in each complaint. Just use it to prioritize explaining this complaint first, and others later. It does not have any special meaning for the algorithm. So, what you can do:

1. In line 2118, just change another list of `no_test`, right now in line 2102: `no_test =  [1]`. 
- You can change to any other numbers/lists. The `sorted_cc.npz` actuaclly does not have any effect on the current code. You can comment it out. 
- If you want to use the sorted list, change line 2118 to: `for i in idx_all:`.

2. If you want to have it, please:
- Remove the comments from line 1893 to 1900, make them visible
    line 1893: # true_truple = [] 
.... 
    line 1900: # return len_
- Remove all lines from line 1901 to 1990
line 1901: num_samples = len(z_strs_list) 
...
line 1990: return accuracy, accuracy2, accuracy3, rn_vect
==> it means now you only want to get the number of ontology-based tuples from each complaint, you do not do any explanation or accuracy...
- Put comment from line 2179 to line 2183 
line 2179: `accuracy, accuracy2, accuracy3, rn_vect = explain_classifier_tf_count(i,..., rn_vect)`
...
line 2183: print('------------ ******** ------------')
- Replace line 2179 with a line  `len_tuples_list = explain_classifier_tf_count(i,..., rn_vect)`
- Then, remove comments from line 2186 to 2194
line 2186: #     if len_tuples_list >=1:
...
line 2194: # np.savez('sorted_cc.npz',idx=idx, idx_all=idx_all,len_all=len_all,sort_idx=sort_idx )
So finally, you will get `sorted_cc.npz`.

Thanks!
